
#undef FUNCNAME_STR
#undef FUNCNAME
#undef FUNCPARAM 
#undef FUNCPARAM_INVOKE
#undef FUNCPARAM_INVOKE_NOPTR
#undef SYSCALL_NUM
#undef DEBUGTEXTPARAM
#undef DEBUGTEXTPARAM_NOPTR
#undef FUNCRETURN
#undef FUNCPARAM_DEBUGTEXT